### ISSUE TITLE
`transit_mode` optional argument for `mp_matrix`

### ISSUE THREAD

**Issue by cseveren** [michaeldorman/mapsapi#15]
Thanks for the package. I would like to request that ability to add an optional argument `transit_mode` to the `mp_matrix` function that queries the Google Maps Distance Matrix API. It's [documentation](https://developers.google.com/maps/documentation/distance-matrix/overview) notes that if `mode=transit`, one can further pass `transit_mode=` one of several options. It appears that your function `mp_directions` already allows this option, so it's likely a simple add.

**Comment by michaeldorman** [comment]
Thanks for your interest in the package! I added a `transit_mode` argument in `mp_matrix`, please let me know if you encounter any issues.

**Comment by cseveren** [comment]
Great, thanks!
-Chris
