### ISSUE TITLE
Same travel time per leg using the three traffic models

### ISSUE THREAD

**Issue by JosephSanchezB** [michaeldorman/mapsapi#17]
First at all, thanks for your contribution (mapsapi)! 

I would like to obtain the travel time (best guess, optimistic, or pessimistic) in EACH LEG. I tried it, but in the three traffic models the results (travel time per leg) are the same.

Could you guide me in this issue?

best regards,

Joseph

doc <-  mp_directions(
  origin = c("-0.249792+-78.52884"),
  destination = c("-0.209296982091499+-78.4914229738011"),
  alternatives = TRUE,
  departure_time = Sys.time(),
  traffic_model = "pessimistic",
  key = key,
  quiet = TRUE
)
seg <-  mp_get_segments(doc)
head(seg)

doc1 <-  mp_directions(
  origin = c("-0.249792+-78.52884"),
  destination = c("-0.209296982091499+-78.4914229738011"),
  alternatives = TRUE,
  departure_time = Sys.time() + (12*3600),
  traffic_model = "best_guess",
  key = key,
  quiet = TRUE
)

seg1 <-  mp_get_segments(doc1)
head(seg1)

**Comment by michaeldorman** [comment]
Thanks! 

This is the expected behavior, since duration in traffic is only returned for each entire route, not for each segment, it is missing from ` mp_get_segments` output. However, the duration in traffic can be obtained via `mp_get_routes`. 

For example, here is the output of `mp_get_routes(doc)`, including the fields `duration_in_traffic_s` and `duration_in_traffic_text`:

```r
route = mp_get_routes(doc) 
route                                                                                                                                    
## Simple feature collection with 3 features and 11 fields
## Geometry type: LINESTRING
## Dimension:     XY
## Bounding box:  xmin: -78.52957 ymin: -0.2499 xmax: -78.48837 ymax: -0.20901
## Geodetic CRS:  WGS 84
##     alternative_id leg_id                                       summary distance_m distance_text duration_s duration_text
## 1-1              1      1                            Av. Velasco Ibarra       8266        8.3 km       1026       17 mins
## 2-1              2      1 Av. Jaime del Castillo and Av. Velasco Ibarra       8668        8.7 km       1031       17 mins
## 3-1              3      1                            Av. Cinco de Junio       6909        6.9 km       1237       21 mins
##     duration_in_traffic_s duration_in_traffic_text departure_time arrival_time                       geometry
## 1-1                  1158                  19 mins           <NA>         <NA> LINESTRING (-78.52886 -0.24...
## 2-1                  1132                  19 mins           <NA>         <NA> LINESTRING (-78.52886 -0.24...
## 3-1                  1179                  20 mins           <NA>         <NA> LINESTRING (-78.52886 -0.24...
```
